Exercise #1 Configuring Connectivity Testing in a Mule Application

When a Mule app starts, it performs a connectivity test on components, such as HTTP or FTP connectors, that require connection to an external server. By default, if the test fails, the application logs a warning message and proceeds with deployment. 
You can modify this behavior by configuring reconnection attempts and specifying  whether deployment should fail if all connection attempts are unsuccessful.
Fail Deployment (failsDeployment): When set to true, this property forces the application deployment to fail if the connection test fails and all configured reconnection attempts are exhausted.
Reconnect (reconnect): Defines the number of reconnection attempts and the interval between them. For example, you can configure 5 reconnection attempts with a frequency of 4000 milliseconds (ms). The default is 2 reconnection attempts every 2000 ms.
Example: Fail Deployment After 5 Reconnection Attempts
The following XML configuration forces deployment to fail after 5 unsuccessful reconnection attempts:
[source,xml]
----
<http:request-config" doc:name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

Reconnect Forever (reconnect-forever): Attempts to reconnect at a specified interval (e.g., every 4000 ms) for as long as the application runs. No limit is set on the number of retries, so the count attribute is not specified. The default interval is 2000 ms.

Example: Unlimited reconnection attempts:
The following XML configuration enables unlimited reconnection attempts:
* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
