# Content Overview: Configuring Connectivity Testing in a Mule Application

## Introduction to Application Startup

On startup, the mule application performs a connectivity test on components, such as HTTP or FTP connectors that require connection to an external server. 
By default, if the test fails, the application logs a warning message but proceeds with deployment. 

This behavior can be modified by configuring reconnection attempts and by specifying that if all connections attempts fails, the application will retry based on predefined configurations.

## Fail Deployment (failsDeployment): 

When the flag is set to true, this property forces the application deployment to fail if the connection test fails and all configured reconnection attempts are exhausted.

## Reconnect (reconnect): 
Defines the number of reconnection attempts and the interval between them. 
For example, you can configure 5 reconnection attempts with a frequency of 4000 milliseconds (ms). The default is 2 reconnection attempts every 2000 ms.

### Example: If the deployment fails after 5 reconnection attempts
The following XML configuration forces deployment to fail after 5 unsuccessful reconnection attempts:
[source,xml]
----
<http:request-config" doc:name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

## Reconnect Forever (reconnect-forever): 
Attempts to reconnect at a specified interval (e.g., every 4000 ms) for as long as the application runs. No limit is set on the number of retries, so the count attribute is not specified. The default interval is 2000 ms.

### Example: Unlimited reconnection attempts:
The following XML configuration enables unlimited reconnection attempts:
* [source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
